var portuguese = [
  "Início",
  "Histórico",
  "Definições",
  "Parece que você ainda não bebeu água hoje...",
  "Selecione um copo",
  "Customizado",
  "Modo Escuro",
  "Linguagem",
  "Adicionar outro valor(ml)",
  "Você já atingiu a meta oficial de 2 litros de água por dia da Organização Mundial da Saúde, mas vamos continuar monitorando! Vamos beber água!",
  "Progresso diário",
  "Meta diária de água:",
  "Definir meta",
  "Total de água no dia:",
  "Meta atual de água:",
  "% da meta concluída",
  "por Ruan Emanuell",
  "Deseja remover esse copo?",
  "Sim",
  "Não",
  "Formato de data Americano",
  "Relógio de 12 Horas"
];

var english = [
  "Home",
  "History",
  "Settings",
  "Looks like you haven't drunk water today...",
  "Select a cup",
  "Custom",
  "Dark Mode",
  "Language",
  "Add other size (ml)",
  "You've already hit the official goal of 2 liters of water per day from the World Health Organization, but we will continue to monitor! Let's drink water!",
  "Daily progress",
  "Daily water goal:",
  "Define goal",
  "Total water for the day:",
  "Current water goal:",
  "% of goal completed",
  "by Ruan Emanuell",
  "Remove from history?",
  "Yes",
  "No",
  "MM-DD-YYYY Date",
  "12-hour clock"
];
